name: Windows Server 2022

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: https://remotedesktop.google.com/headless
        required: true
      pin:
        description: Enter your 6 numbers pin
        required: true
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          ./setting.ps1
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
          Invoke-WebRequest https://eternallybored.org/misc/netcat/netcat-win32-1.11.zip -OutFile nc.zip
          Expand-Archive nc.zip
          powershell
          ls
          cd nc
          ls
          cd netcat-1.11
          ls
          ./nc.exe -v youtube.com 80
          echo enter both ip and port without any  this :
          sleep 80572 
         
    

        
